name: Auto approve PRs

# Trigger the workflow on pull request
on: pull_request

jobs:
  autoapprove:
    name: Auto-Approve a PR
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.CHARTS_GH_BOT_TOKEN }}
